apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.18.0
  name: kube-state-metrics
  namespace: kube-system

---
# to make token permanent (by default token expires after an hour)
apiVersion: v1
kind: Secret
metadata:
  name: kube-state-metrics-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "kube-state-metrics"
type: kubernetes.io/service-account-token